<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>BugNet.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\**\*.xslt">
      <WithCulture>false</WithCulture>
    </EmbeddedResource>
  </ItemGroup>
</Project>
